[package]
name = "axdtb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fdt-rs = { version = "0.4.3", default-features = false }
byteorder = { version = "1.4.3", default-features = false }